Controllers/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Finportal.Data;
using Finportal.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Finportal.Controllers
{
    [Authorize]

    public class BankAccountsController : Controller
    {
        private readonly ApplicationsDbContext _context;
        private readonly UserManager<FPUser> _userManager;

        public BankAccountsController(ApplicationsDbContext context, UserManager<FPUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: BankAccounts
        public async Task<IActionResult> Index()
        {
          

            var user = await _userManager.GetUserAsync(User);
            var accounts = _context.BankAccount.Where(b => b.HouseholdId == user.HouseholdId).ToList();

           

            //if (User.IsInRole("HOH") && User.IsInRole("Member"))
            //{

            //    model = _context.BankAccount
            //        .Include(b => b.CurrentBalance)
            //        .Include(b => b.FPUser).ToList();
            //}


            return View(accounts);
        }

        // GET: BankAccounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankAccount = await _context.BankAccount
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bankAccount == null)
            {
                return NotFound();
            }

            return View(bankAccount);
        }

        // GET: BankAccounts/Create
        //[Authorize(Roles= "HOH, Member")]
        public async Task<IActionResult> Create()
        {
            var account = new BankAccount { HouseholdId = (int)(await _userManager.GetUserAsync(User)).HouseholdId };
            return View(account);
        }

        // POST: BankAccounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HouseholdId,Name,Type,StartingBalance")] BankAccount bankAccount)
        {
            if (ModelState.IsValid)
            {
                bankAccount.FPUserId = _userManager.GetUserId(User);
                bankAccount.CurrentBalance = bankAccount.StartingBalance;
                _context.Add(bankAccount);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details","Households", new { id = bankAccount.HouseholdId });
            }
            return View(bankAccount);
        }

        // GET: BankAccounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankAccount = await _context.BankAccount.FindAsync(id);
            if (bankAccount == null)
            {
                return NotFound();
            }
            return View(bankAccount);
        }

        // POST: BankAccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,HouseholdId,FPUserId,Name,Transaction,Type,StartingBalance,CurrentBalance")] BankAccount bankAccount)
        {
            if (id != bankAccount.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bankAccount);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BankAccountExists(bankAccount.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bankAccount);
        }

        // GET: BankAccounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankAccount = await _context.BankAccount
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bankAccount == null)
            {
                return NotFound();
            }

            return View(bankAccount);
        }

        // POST: BankAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bankAccount = await _context.BankAccount.FindAsync(id);
            _context.BankAccount.Remove(bankAccount);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BankAccountExists(int id)
        {
            return _context.BankAccount.Any(e => e.Id == id);
        }
    }
}

Controllers/TransactionsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Finportal.Data;
using Finportal.Models;
using Microsoft.AspNetCore.Identity;
using Finportal.Services;
using Microsoft.AspNetCore.Authorization;

namespace Finportal.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private readonly ApplicationsDbContext _context;
        private readonly UserManager<FPUser> _userManager;
        private readonly INotificationService _notificationService;

        public TransactionsController(ApplicationsDbContext context, UserManager<FPUser> userManager, INotificationService notificationService)
        {
            _context = context;
            _userManager = userManager;
            _notificationService = notificationService;
        }

        // GET: Transactions
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Transaction.Include(t => t.BankAccount).Include(t => t.CategoryItem).Include(t => t.FPUser);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Transactions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transaction
                .Include(t => t.BankAccount)
                .Include(t => t.CategoryItem)
                .Include(t => t.FPUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // GET: Transactions/Create
        public async Task<IActionResult> Create()
        {
            var householdId = (await _userManager.GetUserAsync(User)).HouseholdId;//null reference
            var myBankAccounts = _context.BankAccount.Where(b => b.HouseholdId == householdId);
            ViewData["BankAccountId"] = new SelectList(myBankAccounts, "Id", "Name");
            ViewData["CategoryItemId"] = new SelectList(_context.CategoryItem, "Id", "Name");
            ViewData["FPUserId"] = new SelectList(_context.Users, "Id", "Name");
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryItemId,BankAccountId,Created,Type,Memo,Amount")] Transaction transaction)
        {


            if (ModelState.IsValid)
            {
                transaction.FPUserId = _userManager.GetUserId(User);
                _context.Add(transaction);
                await _context.SaveChangesAsync();
                //1:Decrease the Bank Current Balance
                var account = await _context.BankAccount.FindAsync(transaction.BankAccountId);
                var oldBalance = account.CurrentBalance;

                if (transaction.Type == Enum.TransactionType.Deposit)
                {
                    account.CurrentBalance += transaction.Amount;
                }
                else
                {
                    //Withdrawl
                    account.CurrentBalance -= transaction.Amount;
                    //2:Increase the Actual Amount of the associated Category Item
                    var categoryItem = await _context.CategoryItem.FindAsync(transaction.CategoryItemId);
                    categoryItem.ActualAmount += transaction.Amount;
                }
                await _context.SaveChangesAsync();
                //3:Look for any needed notifications
                if (account.CurrentBalance < 0)
                {
                    TempData["OverDraft"] = "you overdrft your account. FOO";
                }
                await _notificationService.NotifyOverdraftAsync(transaction, account, oldBalance);
                return RedirectToAction("Details", "Households", new { id = (await _userManager.GetUserAsync(User)).HouseholdId });

            }
            ViewData["BankAccountId"] = new SelectList(_context.BankAccount, "Id", "Name", transaction.BankAccountId);
            ViewData["CategoryItemId"] = new SelectList(_context.CategoryItem, "Id", "Name", transaction.CategoryItemId);
            ViewData["FPUserId"] = new SelectList(_context.Users, "Id", "FullName", transaction.FPUserId);
            return View(transaction);
        }

        // GET: Transactions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transaction.FindAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            ViewData["BankAccountId"] = new SelectList(_context.BankAccount, "Id", "Name", transaction.BankAccountId);
            ViewData["CategoryItemId"] = new SelectList(_context.CategoryItem, "Id", "Name", transaction.CategoryItemId);
            ViewData["FPUserId"] = new SelectList(_context.Users, "Id", "FullName", transaction.FPUserId);
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CategoryItemId,BankAccountId,FPUserId,Created,Type,Memo,Amount,IsDeleted")] Transaction transaction)
        {
            if (id != transaction.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var oldTransaction = _context.Transaction.AsNoTracking().FirstOrDefault(t => t.Id == transaction.Id);

                    _context.Update(transaction);
                  
                    var bankAccount = _context.BankAccount.Find(transaction.BankAccountId);
                    if (oldTransaction.Amount > transaction.Amount)
                    {
                        var result = oldTransaction.Amount - transaction.Amount;
                        bankAccount.CurrentBalance += result;
                        _context.Update(bankAccount);
                    }
                    else
                    {
                        var result = oldTransaction.Amount - transaction.Amount;

                        bankAccount.CurrentBalance += result;
                        _context.Update(bankAccount);
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransactionExists(transaction.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BankAccountId"] = new SelectList(_context.BankAccount, "Id", "Name", transaction.BankAccountId);
            ViewData["CategoryItemId"] = new SelectList(_context.CategoryItem, "Id", "Id", transaction.CategoryItemId);
            ViewData["FPUserId"] = new SelectList(_context.Users, "Id", "Id", transaction.FPUserId);
            return View(transaction);
        }

        // GET: Transactions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transaction
                .Include(t => t.BankAccount)
                .Include(t => t.CategoryItem)
                .Include(t => t.FPUser)
                .FirstOrDefaultAsync(m => m.Id == id);


            var account = await _context.BankAccount.Include(t => t.Household).FirstOrDefaultAsync(t => t.Id == transaction.BankAccountId);

            account.CurrentBalance += transaction.Amount;
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var transaction = await _context.Transaction.FindAsync(id);

            var account = await _context.BankAccount.Include(t => t.Household).FirstOrDefaultAsync(t => t.Id == transaction.BankAccountId);

            account.CurrentBalance += transaction.Amount;

            _context.Transaction.Remove(transaction);

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Households", new { id = account.HouseholdId });
        }

        private bool TransactionExists(int id)
        {
            return _context.Transaction.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<FPUser> UserManager
@{
    var userId = await UserManager.GetUserAsync(User);
    <!--OverDraft Message-->
    var message = (string)TempData["OverDraft"];


}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Finportal</title>
    <!--Loader-->
    <link href="~/css/Loader/loader.css" rel="stylesheet" type="text/css" />
    <script src="~/js/Loader/js/loader.js"></script>
    <!--End Loader-->
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,600,700&display=swap" rel="stylesheet">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    @*<link href="~/css/plugins.css" rel="stylesheet" type="text/css" />*@
    <link href="~/css/structure.css" rel="stylesheet" type="text/css" class="structure" />
    <link href="~/css/form-2.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM STYLES -->
    <link href="~/css/dash_2.css" rel="stylesheet" type="text/css" class="dashboard-sales" />
    <!-- END PAGE LEVEL PLUGINS/CUSTOM STYLES -->
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
    <!--Table-->
    <link href="~/css/Table/datatables.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Table/custom_dt_html5.css" rel="stylesheet" type="text/css" />
    <!--Chart-->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">

    <link href="~/css/ToolTip/tooltip.css" rel="stylesheet" />



    <link href="~/css/alert.css" rel="stylesheet" type="text/css" />
</head>
<body class="sidebar-noneoverflow background ">
    <!-- BEGIN LOADER -->
    <div id="load_screen">
        <div class="loader">
            <div class="loader-content">
                <div class="spinner-grow align-self-center"></div>
            </div>
        </div>
    </div>
    <!--  END LOADER -->
    <!--Begin Top Nav-->
    @if (User.Identity.IsAuthenticated)
    {
        <div class="header-container fixed-top">
            <header class="header navbar navbar-expand-sm bg-dark">
                <ul class="navbar-item flex-row">
                    <li class="">
                    </li>
                </ul>

                @*<a href="javascript:void(0);" class="sidebarCollapse" data-placement="bottom"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-list"><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3" y2="6"></line><line x1="3" y1="12" x2="3" y2="12"></line><line x1="3" y1="18" x2="3" y2="18"></line></svg></a>*@


                <ul class="navbar-item flex-row navbar-dropdown">
                    <div class="container">
                        <a class="navbar-brand navtextcolor" asp-area="" asp-controller="Households" asp-action="Details" asp-route-id="@((await UserManager.GetUserAsync(User)).HouseholdId)">Save 'N Money</a>


                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span ><i class="fas fa-wallet">   </i></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                            <ul class="navbar-nav flex-grow-1">
                                @if (User.IsInRole("HOH") || User.IsInRole("Member"))
                                {

                                    <li class="nav-item">
                                        <a class="nav-link navtextcolor" asp-area="" asp-controller="Households" asp-action="Details" asp-route-id="@((await UserManager.GetUserAsync(User)).HouseholdId)">Household</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link navtextcolor" asp-area="" asp-controller="Invitations" asp-action="Create">Invitations</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link navtextcolor" asp-area="" asp-controller="BankAccounts" asp-action="Index">Bank Account</a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="nav-link navtextcolor" asp-area="" asp-controller="Transactions" asp-action="Create">Transaction</a>
                                    </li>
                                }
                                <li class="nav-item dropdown">
                                    <a href="https://jonathanportfolio.netlify.app/" class="nav-link navtextcolor">Portfolio</a>
                                </li>
                            </ul>
                            <partial name="_LoginPartial" />
                        </div>
                    </div>

                </ul>
            </header>
        </div>
    }

    <!--End Top Nav-->
    <!--Begin Side Nav-->
    <!--End side Nav-->

    <div class="main-container justify-content-center" id="container">
        <div class="overlay"></div>
        <div class="search-overlay"></div>
        <div class="main-content content">
            <div class="layout-px-spacing">
                <main role="main" class="pb-3">
                    @if (TempData["OverDraft"] != null)
                    {
                        <div class="alert alert-icon-right alert-light-primary mb-4" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><svg data-dismiss="alert"> ... </svg></button>
                            <svg> ... </svg>
                            <strong>Warning!</strong> @userId.FirstName overdrafted your account!
                        </div>
                    }
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    @if (User.Identity.IsAuthenticated)
    {

        <footer class="bg-dark py-4">
            <div class="container">
                <div class="row py-2">
                    <div class="col-lg-6 text-center text-lg-left mb-2 mb-lg-0">
                        <p class="small text-muted text-uppercase mb-0">&copy; Jonathan Green - all rights reserved</p>
                    </div>
                    <div class="col-lg-6 text-center mb-2 mb-lg-0 ">
                        <ul class="list-inline text-white small mb-0 footerIconGrowHover footerIconGrow">
                            <li class="list-inline-item">
                                <a class="reset-anchor" target="_blank" href="https://github.com/october464">
                                    <i class="fab fa-github"></i>
                                </a>
                            </li>

                            <li class="list-inline-item footerIconGrowHover footerIconGrow">
                                <a class="reset-anchor" target="_blank" href="https://www.linkedin.com/in/jonathan-green-854723164/">
                                    <i class="fab fa-linkedin"></i>
                                </a>
                            </li>

                            <li class="list-inline-item footerIconGrowHover footerIconGrow">
                                <a class="reset-anchor" target="_blank" href="https://twitter.com/Jonatha20659564">
                                    <i class="fab fa-twitter"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    }
    <!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
    <script src="~/js/jquery-3.1.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/form-2.js"></script>

    @*<script src="~/js/app.js"></script>*@
    @*<script>
            $(document).ready(function () {
                App.init();
            });
        </script>*@

    <script src="~/js/ToolTip/tooltip.js"></script>
    <!--Chart-->
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

    <script src="~/css/Table/datatables.js"></script>
    <!--Table-->
    <script src="~/css/Table/dataTables.buttons.min.js"></script>
    <script src="~/css/Table/jszip.min.js"></script>
    <script src="~/css/Table/buttons.html5.min.js"></script>
    <script src="~/css/Table/buttons.print.min.js"></script>
    <script>
        $('table').DataTable({
            dom: '<"row"<"col-md-12"<"row"<"col-md-6"B><"col-md-6"f> > ><"col-md-12"rt> <"col-md-12"<"row"<"col-md-5"i><"col-md-7"p>>> >',
            buttons: {
                buttons: [
                    { extend: 'copy', className: 'btn' },
                    { extend: 'csv', className: 'btn' },
                    { extend: 'excel', className: 'btn' },
                    { extend: 'print', className: 'btn' }
                ]
            },
            "oLanguage": {
                "oPaginate": { "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' },
                "sInfo": "Showing page _PAGE_ of _PAGES_",
                "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                "sSearchPlaceholder": "Search...",
                "sLengthMenu": "Results :  _MENU_",
            },
            "stripeClasses": [],
            "lengthMenu": [7, 10, 20, 50],
            "pageLength": 7
        });
    </script>





    @*@if (!string.IsNullOrWhiteSpace(message))
        {
            <script>
                 $(document).ready(function alertFn() {
                     swal("@TempData["OverDraft"]")
                 });
            </script>
        }*@

    <!-- END GLOBAL MANDATORY SCRIPTS -->
    <!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->
    @*<script src="~/js/dash_2.js"></script>*@
    <!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->

    @RenderSection("Scripts", required: false)
</body>
</html>